// src/features/inspection-management/domain/models/InspectionSession.ts

export type InspectionSessionStatus =
  | "SCHEDULED"
  | "IN_PROGRESS"
  | "COMPLETED"
  | "CANCELLED";

export interface InspectionSession {
  id: string;
  /** FK → tpi_requests.id */
  tpi_request_id: string;
  /** Auto-increment per request (1, 2, 3...) */
  session_number: number;
  /** Date of this inspection visit */
  session_date: string;
  /** Snapshot of stages selected for this session */
  stages: string[];
  /** Snapshot of methods selected for this session */
  methods: string[];
  /** Snapshot of equipment ids selected for this session */
  equipment_ids: string[];
  status: InspectionSessionStatus;
  /** Optional sub-vendor; empty by default (main vendor comes from the request) */
  sub_vendor?: string;
  notes?: string;
  /** Soft-deleted sessions remain persisted for traceability. */
  is_deleted?: boolean;
  deleted_at?: string | null;
  deleted_by?: string | null;
  deletion_reason?: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * Command object for creating a new session.
 * session_number and id are generated by the application layer.
 */
export interface CreateSessionCommand {
  tpi_request_id: string;
  session_date: string;
  stages: string[];
  methods: string[];
  equipment_ids: string[];
  sub_vendor?: string;
  notes?: string;
}

export interface DeleteInspectionSessionCommand {
  deleted_by: string;
  reason: string;
}
