// src/shared/authorization/ui/elements/ContractElements.ts

import type { UIModuleElements } from "../types";

export const ContractElements: UIModuleElements = {
  ContractList: {
    list_item_view: {
      id: "contract_list_item_view",
      label: "View Contract Item",
      type: "action",
      category: "navigation",
      requires: [],
    },
    list_item_click: {
      id: "contract_list_item_click",
      label: "Clickable Contract Item",
      type: "action",
      category: "navigation",
      requires: ["ContractList.list_item_view"],
    },
    search_box: {
      id: "contract_search_box",
      label: "Contract Search Box",
      type: "search",
      category: "filtering",
      requires: ["ContractList.list_item_view"],
    },
    filter_type: {
      id: "contract_filter_type",
      label: "Contract Type Filter",
      type: "filter",
      category: "filtering",
      requires: ["ContractList.list_item_view"],
    },
    filter_status: {
      id: "contract_filter_status",
      label: "Contract Status Filter",
      type: "filter",
      category: "filtering",
      requires: ["ContractList.list_item_view"],
    },
    status_badge: {
      id: "contract_status_badge",
      label: "Contract Status Badge",
      type: "badge",
      category: "information",
      requires: ["ContractList.list_item_view"],
    },
    list_value: {
      id: "contract_list_value",
      label: "Contract List Value",
      type: "statistic",
      category: "analytics",
      requires: ["ContractList.list_item_view"],
    },
    dates: {
      id: "contract_dates",
      label: "Contract Dates in List",
      type: "information",
      category: "information",
      requires: ["ContractList.list_item_view"],
    },
    progress_bar: {
      id: "contract_progress_bar",
      label: "Contract Progress Bar",
      type: "progress",
      category: "analytics",
      requires: ["ContractList.list_item_view"],
    },
    btn_add: {
      id: "contract_btn_add",
      label: "Add Contract Button",
      type: "button",
      category: "crud",
      requires: ["ContractList.list_item_view"],
    },
    btn_export: {
      id: "contract_btn_export",
      label: "Export Contracts Button",
      type: "button",
      category: "reporting",
      requires: ["ContractList.list_item_view"],
    },
  },
  ContractDetails: {
    details_view: {
      id: "contract_details_view",
      label: "View Contract Details",
      type: "page",
      category: "navigation",
      requires: ["ContractList.list_item_click"],
    },
    info_section: {
      id: "contract_details_info",
      label: "Contract Information",
      type: "section",
      category: "information",
      requires: ["ContractDetails.details_view"],
    },
    tariffs_section: {
      id: "contract_details_tariffs",
      label: "Tariffs Section",
      type: "section",
      category: "information",
      requires: ["ContractDetails.details_view"],
    },
    tariffs_add: {
      id: "contract_details_tariffs_add",
      label: "Add Tariff",
      type: "button",
      category: "crud",
      requires: ["ContractDetails.tariffs_section"],
    },
    tariffs_edit: {
      id: "contract_details_tariffs_edit",
      label: "Edit Tariff",
      type: "button",
      category: "crud",
      requires: ["ContractDetails.tariffs_section"],
    },
    tariffs_delete: {
      id: "contract_details_tariffs_delete",
      label: "Delete Tariff",
      type: "button",
      category: "crud",
      requires: ["ContractDetails.tariffs_section"],
    },
    amendments_section: {
      id: "contract_details_amendments",
      label: "Amendments Section",
      type: "section",
      category: "workflow",
      requires: ["ContractDetails.details_view"],
    },
    amendments_add: {
      id: "contract_details_amendments_add",
      label: "Add Amendment",
      type: "button",
      category: "crud",
      requires: ["ContractDetails.amendments_section"],
    },
    amendments_approve: {
      id: "contract_details_amendments_approve",
      label: "Approve Amendment",
      type: "button",
      category: "approval",
      requires: ["ContractDetails.amendments_section"],
    },
    amendments_reject: {
      id: "contract_details_amendments_reject",
      label: "Reject Amendment",
      type: "button",
      category: "approval",
      requires: ["ContractDetails.amendments_section"],
    },
    stats_section: {
      id: "contract_details_stats",
      label: "Contract Statistics",
      type: "section",
      category: "analytics",
      requires: ["ContractDetails.details_view"],
    },
    btn_edit: {
      id: "contract_btn_edit",
      label: "Edit Contract",
      type: "button",
      category: "crud",
      requires: ["ContractDetails.details_view"],
    },
    btn_amend: {
      id: "contract_btn_amend",
      label: "Amend Contract",
      type: "button",
      category: "crud",
      requires: ["ContractDetails.details_view"],
    },
    btn_approve: {
      id: "contract_btn_approve",
      label: "Approve Contract",
      type: "button",
      category: "approval",
      requires: ["ContractDetails.details_view"],
    },
    btn_doc: {
      id: "contract_btn_doc",
      label: "View Contract Documents",
      type: "button",
      category: "information",
      requires: ["ContractDetails.details_view"],
    },
    info_start_date: {
      id: "contract_info_start_date",
      label: "Contract Start Date",
      type: "information",
      category: "information",
      requires: ["ContractDetails.info_section"],
    },
    info_end_date: {
      id: "contract_info_end_date",
      label: "Contract End Date",
      type: "information",
      category: "information",
      requires: ["ContractDetails.info_section"],
    },
    stat_total_value: {
      id: "contract_stat_total_value",
      label: "Contract Total Value Stat",
      type: "statistic",
      category: "analytics",
      requires: ["ContractDetails.stats_section"],
    },
    stat_performed_work: {
      id: "contract_stat_performed_work",
      label: "Contract Performed Work Stat",
      type: "statistic",
      category: "analytics",
      requires: ["ContractDetails.stats_section"],
    },
    stat_invoiced: {
      id: "contract_stat_invoiced",
      label: "Contract Invoiced Stat",
      type: "statistic",
      category: "analytics",
      requires: ["ContractDetails.stats_section"],
    },
    stat_not_invoiced: {
      id: "contract_stat_not_invoiced",
      label: "Contract Not Invoiced Stat",
      type: "statistic",
      category: "analytics",
      requires: ["ContractDetails.stats_section"],
    },
    progress_work: {
      id: "contract_progress_work",
      label: "Contract Work Progress",
      type: "progress",
      category: "analytics",
      requires: ["ContractDetails.stats_section"],
    },
    progress_invoice: {
      id: "contract_progress_invoice",
      label: "Contract Invoice Progress",
      type: "progress",
      category: "analytics",
      requires: ["ContractDetails.stats_section"],
    },
    progress_time: {
      id: "contract_progress_time",
      label: "Contract Time Progress",
      type: "progress",
      category: "analytics",
      requires: ["ContractDetails.stats_section"],
    },
    reminder_section: {
      id: "contract_reminder_section",
      label: "Contract Reminder Section",
      type: "section",
      category: "information",
      requires: ["ContractDetails.details_view"],
    },
    table_tariffs: {
      id: "contract_table_tariffs",
      label: "Contract Tariffs Table",
      type: "table",
      category: "information",
      requires: ["ContractDetails.tariffs_section"],
    },
  },
};
