// src/features/contract-management/elements.ts

export const contractElements = {
  ContractList: {
    list_item_view: "View Contract List",
    list_item_click: "Click Contract Item",
    search_box: "Search Box",
    filter_type: "Type Filter Tabs",
    filter_status: "Status Filter Tabs",
    status_badge: "Contract Status Badge",
    list_value: "Contract Value in List",
    progress_bar: "Time Progress Bar",
    contract_dates: "Contract Dates",
    btn_add: "Add Contract Button",
    btn_export: "Export Contracts Button",
  },

  ContractDetails: {
    btn_edit: "Edit Contract Button",
    btn_delete: "Delete Contract Button",
    btn_approve: "Approve Contract Button - Only for Manager",
    info_section: "Contract Information Section",
    info_start_date: "Start Date Display",
    info_end_date: "End Date Display",
    stat_total_value: "Total Value Stat",
    stat_performed_work: "Total Performed Work Stat",
    stat_invoiced: "Invoiced Stat",
    stat_not_invoiced: "Not Invoiced Stat",
    progress_work: "Work Progress Bar",
    progress_invoice: "Invoice Progress Bar",
    progress_time: "Time Progress Bar",
    reminder_section: "Adjustment Reminder Section",
    table_tariffs: "Tariffs Table",
  },

  ContractEditForm: {
    modal_edit: "Edit Contract Modal",
    field_type: "Type Selector (Contract/Work Order)",
    field_client: "Client Selector",
    field_title: "Contract Title Field",
    field_service_description: "Service Description Field",
    field_dates: "Start/End Date Fields",
    field_contract_no: "Contract Number Fields",
    field_total_value: "Total Value Field",
    field_currency: "Currency Field",
    field_tariffs: "Tariffs Section",
    field_financial_terms: "Financial Terms Section",
    field_adjustment: "Price Adjustment Section",
    field_modification: "Contract Modification Section",
    field_guarantee: "Guarantee Section",
    field_good_performance: "Good Performance Field",
    field_insurance: "Insurance Deduction Field",
    field_attachments: "Attachments Section",
    field_description: "Description Field",
    field_source_type: "Source Type Selector (Letter/Email)",
    field_letter: "Letter Fields (Number, Date, Image)",
    field_email_source: "Email Fields (From, Date, File)",
  },
};

export const contractPermissionGroups = {
  financial: [
    "contract_list_value",
    "contract_stat_total_value",
    "contract_stat_performed_work",
    "contract_stat_invoiced",
    "contract_stat_not_invoiced",
    "contract_table_tariffs",
    "contract_field_total_value",
    "contract_field_currency",
    "contract_field_tariffs",
    "contract_field_financial_terms",
    "contract_field_adjustment",
    "contract_field_modification",
    "contract_field_guarantee",
    "contract_field_good_performance",
    "contract_field_insurance",
  ],

  edit: [
    "contract_btn_edit",
    "contract_field_type",
    "contract_field_client",
    "contract_field_title",
    "contract_field_service_description",
    "contract_field_dates",
    "contract_field_contract_no",
    "contract_field_attachments",
    "contract_field_description",
    "contract_field_source_type",
    "contract_field_letter",
    "contract_field_email_source",
  ],

  approve: ["contract_btn_approve"],

  delete: ["contract_btn_delete"],
};

export default contractElements;
